Keep as much color codes out of the locale files as possible
NetherGamesMC/locale pull request #20
Opened 2023-01-22 01:17 UTC by japakkjj

§§a is the alternative color
§§m is the main color

2023-01-23 07:34 UTC, japakkjj commented
@hampuskraft But is it right?

2023-01-23 07:35 UTC, hampuskraft commented
Be patient. I'll review it when I've got time.

2023-02-01 05:40 UTC, japakkjj commented
> Be patient. I'll review it when I've got time.

Ok

2023-02-04 10:22 UTC, DidntPot approved these changes

2023-02-04 20:11 UTC, japakkjj commented
Nice

Enviado do meu iPhone

> Em 4 de fev. de 2023, à(s) 07:22, DidntPot ***@***.***> escreveu:
> 
> ﻿
> @DidntPot approved this pull request.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2023-02-18 16:51 UTC, japakkjj commented
@hampuskraft  anything new?

2023-02-18 21:07 UTC, hampuskraft requested changes

2023-02-18 21:07 UTC, hampuskraft commented on portuguese.json
> +    "forms.settings.hideplayers": "Ocultar Jogadores",
"Jogadores" shouldn't be capitalized here.

2023-02-18 21:07 UTC, hampuskraft commented on portuguese.json
> +    "forms.teleporter.partly_online": "PARTLY ONLINE",
Ironically, this seems to be partly translated—how about "EM PARTE ONLINE"?

2023-02-18 21:20 UTC, hampuskraft commented on portuguese.json
> +    "global.nothere": "Não pode fazer isso aqui.",
Resolved in [`2f8c82b` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/2f8c82b3539fc568fdacb2d23c8da45451ef9526).

2023-02-19 09:43 UTC, hampuskraft commented on portuguese.json
> +    "skywars.setup.enter_middle_chest_setup_mode": "Modo de configuração do baú para: {%arena}\nTap baús para adicionar ao baú central ou usar comando '/sw editar set do baú de id para parar.",
This translation is incorrect. The original string is "Entered chest configuration mode for: {%arena}\nTap chests to add to middle chests or use command '/sw edit setmidchest' to stop."

2023-02-19 09:45 UTC, hampuskraft commented
@japakkjj As you can see, I've added plenty of comments. Please resolve these before we can merge your PR. Let me know if you have any questions. Otherwise, Google is your friend.

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.accepted.receiver": "Aceite o pedido de {%sender} para se teleportarem para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tell.sender": "O senhor sussurrou para {%receiver}: {%message}",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "forms.teleporter.partly_online": "PARTLY ONLINE",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.hiding": "escondido",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.guildtag": "Agora é {%enabledOrDisabled} your guild tag.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.norequest": "Aquele jogador não enviou um pedido para que se teletransporte para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.declined.sender": "{%receiver} recusou o seu pedido para que eles se teleportassem para você.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tell.yourself": "você não pode enviar uma mensagem a si mesmo.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.accepted.receiver": "Aceite o pedido de {%sender} para se teleportarem para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.friends": "Agora vocês {%enabledOrDisabled} São amigos.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.accepted.sender": "{%receiver} aceitou o seu pedido para que eles se teletransportem para você.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.declined.receiver": "recusou o pedido de {%sender} para que se teleportasse para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.declined.sender": "{%receiver} recusou o seu pedido para que eles se teleportassem para você.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.norequest": "Aquele jogador não enviou um pedido para que se teletransporte para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tphere.receive": "{%sender} Pediu que se teleportasse para eles! Use §§a/tphere aceitar {%sender} para aceitar o pedido.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tpto.accepted.receiver": "Aceitou o pedido de {%sender} para que eles se teletransportem para você.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tpto.accepted.sender": "{%receiver} aceitou o seu pedido para que se teletransportasse para eles.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tpto.declined.receiver": "Recusou o pedido de {%sender} para que eles se teletransportassem para você.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.tpto.noperm": "Não tem autorização para efetuar a teletransportação para outros jogadores. Adquira o passe §l§aEMERALD§r §§mor §l§bLEGEND§r §§mrank em  §§angmc.co/store §§mno site!",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:05 UTC, hampuskraft commented on portuguese.json
> +    "command.vanish.enabled": "Agora você está invisivel",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.fly": "{%enabledOrDisabled} voar no lobby.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.fly.hidingrank": "Você não pode voar enquanto estiver usando um nome falso ou a esconder a sua posição de rank.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.friends": "Agora vocês {%enabledOrDisabled} São amigos.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.hiding": "escondido",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.hideplayers": "You are now {%enabledOrDisabled} players.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.pet.selected": "O seu pet de estimação foi mudado para um {%pet}.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "formhandler.settings.guildtag": "Agora é {%enabledOrDisabled} your guild tag.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "forms.settings.hideplayers": "Ocultar Jogadores",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "forms.teleporter.partly_online": "PARTLY ONLINE",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:06 UTC, hampuskraft commented on portuguese.json
> +    "skywars.setup.enter_middle_chest_setup_mode": "Modo de configuração do baú para: {%arena}\nTap baús para adicionar ao baú central ou usar comando '/sw editar set do baú de id para parar.",
Resolved in [`3ea86c1` (#20)](https://github.com/NetherGamesMC/locale/pull/20/commits/3ea86c1437d4531c57431ef25b74aa5f3056cf10).

2023-02-21 12:11 UTC, hampuskraft approved these changes

2023-02-21 12:13 UTC, hampuskraft commented
I handled all requested changes. Feel free to submit a PR if you would like to improve the fluency of something or other possible errors. Thanks!

2023-02-21 12:13 UTC, merged

2023-02-21 16:16 UTC, japakkjj commented
Sorry for not answering, I was at the carnival, I saw you changed some things, could you chat with me at discord? Luk#8903
Enviado do meu iPhone

> Em 21 de fev. de 2023, à(s) 09:13, Hampus Kraft ***@***.***> escreveu:
> 
> ﻿
> Merged #20 into master.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2023-02-21 16:23 UTC, hampuskraft commented
If you would like to edit something, feel free to submit a new PR.

2023-02-21 16:27 UTC, japakkjj commented
Ok, I'll send it to you and let you know, but you don't accept discord chat, do you?

Enviado do meu iPhone

> Em 21 de fev. de 2023, à(s) 13:23, Hampus Kraft ***@***.***> escreveu:
> 
> If you would like to edit something, feel free to submit a new PR.

2023-02-21 17:36 UTC, japakkjj commented
Finished.